version: "3.7"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    networks:
      - nginx_network
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./app/
    deploy:
      replicas: 2
      resources:
          limits:
              cpus: '0.5'
              memory: 256M

    volumes:
      - ./app/:/usr/src/app
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - 8000
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs/:/var/log/nginx/
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    depends_on:
      - database
      - app

    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge