version: "3.7"

services:
  db:
    image: postgres
    container_name: "application_database_postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - nginx_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  djangoapp:
    build:
      context: .
#      dockerfile: app.dockerfile
    deploy:
      replicas: 2
      resources:
          limits:
              cpus: '0.5'
              memory: 512M

    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000
    networks:
      - nginx_network

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs/:/var/log/nginx/
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    depends_on:
      - db
      - djangoapp

    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge